use anchor_lang::prelude::*;

// Replace this with the Program ID generated by Solana Playground
declare_id!("11111111111111111111111111111111");

#[program]
pub mod tasky {
    use super::*;

    pub fn create_task(
        ctx: Context<CreateTask>,
        task_id: String,
        title: String,
        description: String,
        category: String,
        lamports: u64,
    ) -> Result<()> {
        let task = &mut ctx.accounts.task;
        task.creator = *ctx.accounts.creator.key;
        task.helper = Pubkey::default();
        task.status = 0; // 0: Open
        task.lamports = lamports;
        task.task_id = task_id;
        task.title = title;
        task.description = description;
        task.category = category;
        task.created_at = Clock::get()?.unix_timestamp;

        // Transfer funds from creator to the task PDA (escrow)
        let ix = anchor_lang::solana_program::system_instruction::transfer(
            &ctx.accounts.creator.key(),
            &task.key(),
            lamports,
        );
        anchor_lang::solana_program::program::invoke(
            &ix,
            &[
                ctx.accounts.creator.to_account_info(),
                task.to_account_info(),
            ],
        )?;

        Ok(())
    }

    pub fn accept_task(ctx: Context<AcceptTask>) -> Result<()> {
        let task = &mut ctx.accounts.task;
        require!(task.status == 0, ErrorCode::InvalidStatus);
        
        task.helper = *ctx.accounts.helper.key;
        task.status = 1; // 1: In Progress
        task.accepted_at = Clock::get()?.unix_timestamp;

        Ok(())
    }

    pub fn release_funds(ctx: Context<ReleaseFunds>) -> Result<()> {
        let task = &mut ctx.accounts.task;
        require!(task.status == 1, ErrorCode::InvalidStatus);
        require!(task.creator == *ctx.accounts.creator.key, ErrorCode::Unauthorized);

        task.status = 2; // 2: Completed
        task.completed_at = Clock::get()?.unix_timestamp;

        // Transfer funds from PDA to helper
        let lamports = task.lamports;
        **task.to_account_info().try_borrow_mut_lamports()? -= lamports;
        **ctx.accounts.helper.try_borrow_mut_lamports()? += lamports;

        Ok(())
    }

    pub fn raise_dispute(ctx: Context<RaiseDispute>) -> Result<()> {
        let task = &mut ctx.accounts.task;
        require!(task.status == 1, ErrorCode::InvalidStatus);
        require!(
            task.creator == *ctx.accounts.signer.key || task.helper == *ctx.accounts.signer.key,
            ErrorCode::Unauthorized
        );

        task.status = 4; // 4: Disputed
        Ok(())
    }

    pub fn admin_resolve(ctx: Context<AdminResolve>, release_to_helper: bool) -> Result<()> {
        let task = &mut ctx.accounts.task;
        require!(task.status == 4, ErrorCode::InvalidStatus);

        // NOTE: In production, verify the admin pubkey via a constant or config account!
        // For the hackathon demo, we check if the signer matches a known admin.
        // Replace "ADMIN_PUBKEY" below with the actual wallet pubkey you use to test the admin panel.
        // require!(*ctx.accounts.admin.key == pubkey!("ADMIN_PUBKEY"), ErrorCode::Unauthorized);

        let lamports = task.lamports;
        **task.to_account_info().try_borrow_mut_lamports()? -= lamports;

        if release_to_helper {
            task.status = 2; // Completed
            **ctx.accounts.helper.try_borrow_mut_lamports()? += lamports;
        } else {
            task.status = 3; // Cancelled/Refunded
            **ctx.accounts.creator.try_borrow_mut_lamports()? += lamports;
        }
        task.completed_at = Clock::get()?.unix_timestamp;

        Ok(())
    }

    pub fn cancel_task(ctx: Context<CancelTask>) -> Result<()> {
        let task = &mut ctx.accounts.task;
        require!(task.status == 0, ErrorCode::InvalidStatus); // Must be Open
        require!(task.creator == *ctx.accounts.creator.key, ErrorCode::Unauthorized);

        task.status = 3; // 3: Cancelled
        task.completed_at = Clock::get()?.unix_timestamp;

        // Refund SOL to creator
        let lamports = task.lamports;
        **task.to_account_info().try_borrow_mut_lamports()? -= lamports;
        **ctx.accounts.creator.try_borrow_mut_lamports()? += lamports;

        Ok(())
    }

    pub fn edit_task(
        ctx: Context<EditTask>,
        title: String,
        description: String,
        category: String,
    ) -> Result<()> {
        let task = &mut ctx.accounts.task;
        require!(task.status == 0, ErrorCode::InvalidStatus); // Must be Open
        require!(task.creator == *ctx.accounts.creator.key, ErrorCode::Unauthorized);

        task.title = title;
        task.description = description;
        task.category = category;

        Ok(())
    }
}

#[derive(Accounts)]
#[instruction(task_id: String)]
pub struct CreateTask<'info> {
    #[account(
        init,
        payer = creator,
        space = 8 + TaskAccount::INIT_SPACE,
        seeds = [b"task", creator.key().as_ref(), task_id.as_bytes()],
        bump
    )]
    pub task: Account<'info, TaskAccount>,
    #[account(mut)]
    pub creator: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct AcceptTask<'info> {
    #[account(mut)]
    pub task: Account<'info, TaskAccount>,
    #[account(mut)]
    pub helper: Signer<'info>,
}

#[derive(Accounts)]
pub struct ReleaseFunds<'info> {
    #[account(mut, has_one = creator)]
    pub task: Account<'info, TaskAccount>,
    #[account(mut)]
    pub creator: Signer<'info>,
    /// CHECK: This is safe because we just transfer lamports to it
    #[account(mut, address = task.helper)]
    pub helper: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct RaiseDispute<'info> {
    #[account(mut)]
    pub task: Account<'info, TaskAccount>,
    pub signer: Signer<'info>,
}

#[derive(Accounts)]
pub struct AdminResolve<'info> {
    #[account(mut)]
    pub task: Account<'info, TaskAccount>,
    pub admin: Signer<'info>,
    /// CHECK: Target for refund
    #[account(mut, address = task.creator)]
    pub creator: AccountInfo<'info>,
    /// CHECK: Target for release
    #[account(mut, address = task.helper)]
    pub helper: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct CancelTask<'info> {
    #[account(mut, has_one = creator)]
    pub task: Account<'info, TaskAccount>,
    #[account(mut)]
    pub creator: Signer<'info>,
}

#[derive(Accounts)]
pub struct EditTask<'info> {
    #[account(mut, has_one = creator)]
    pub task: Account<'info, TaskAccount>,
    pub creator: Signer<'info>,
}

#[account]
pub struct TaskAccount {
    pub creator: Pubkey,
    pub helper: Pubkey,
    pub status: u8,
    pub lamports: u64,
    pub created_at: i64,
    pub accepted_at: i64,
    pub completed_at: i64,
    pub task_id: String,
    pub title: String,
    pub description: String,
    pub category: String,
}

impl TaskAccount {
    // 32 (creator) + 32 (helper) + 1 (status) + 8 (lamports) + 8 (created_at) + 8 (accepted_at) + 8 (completed_at) + strings
    pub const INIT_SPACE: usize = 32 + 32 + 1 + 8 + 8 + 8 + 8 + (4 + 50) + (4 + 100) + (4 + 300) + (4 + 30);
}

#[error_code]
pub enum ErrorCode {
    #[msg("Invalid task status for this operation.")]
    InvalidStatus,
    #[msg("Unauthorized access.")]
    Unauthorized,
}
